[build]
  # Build command for Next.js with Netlify plugin
  command = "npm run build"
  # Functions directory for serverless functions
  functions = "netlify/functions"

[build.environment]
  # Node.js version (Netlify supported version)
  NODE_VERSION = "18"
  # Next.js environment
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect rules handled by Next.js

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    X-DNS-Prefetch-Control = "on"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes redirect to Netlify Functions
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/admin/auth/login"
  to = "/.netlify/functions/admin-auth"
  status = 200

# Form processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Edge functions (if needed)
[functions]
  directory = "netlify/functions"

# Netlify plugins
[[plugins]]
  package = "@netlify/plugin-functions-install-core"